"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
APP = ['Spotium.py']
DATA_FILES = ['background.png', 'btn-block.png', 'btn-unblock.png', 'loading.png', 'exit.png', 'patch.sh', 'unpatch.sh']
OPTIONS = {'iconfile': 'icon.icns', 'includes': ['tkinter', 'time', 'os', 'sys', 'pwd', 'subprocess'],}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
